### ISSUE TITLE
Username from theme options

### ISSUE THREAD

**Issue by sentisoft** [fooplugins/FooTweetFetcher#1]
Can you pelase help me how to add my username from theme options.. I add field in Theme option and on some part of theme I call with this code get_option('swt_twitter_link') but when I try this to add instead $meta["twitterUser"] I get error and its not work.. can you help me to add username please?

**Comment by sentisoft** [comment]
I forget to say thank you for this great script :)

**Comment by bradvin** [comment]
@sentisoft you could try the following:

``` php
<?php

require_once 'twitteroauth.php';
require_once 'FooTweetFetcher.php';

$twitter_consumer_key = 'YUsyMo5NicXhE4v1WrxdPb';
$twitter_consumer_secret = 'GTFbRUwmzaQ81xLvhYkXfONCyEdSsIZoVDrqMn5g';
$twitter_access_key = '393392201-UnWGXxQYOwJsdaycrbIztpVlEq2kZMHvR64hKPoi';
$twitter_access_secret = 'PNquKXvpgYGcDRilrwFZtSHsUWjCOTeAJf28EM0oQ';

//create a new instance
$fetcher = new FooTweetFetcher($twitter_consumer_key, $twitter_consumer_secret, $twitter_access_key, $twitter_access_secret);
$args = array(
    'limit'            => 10,   //get 10 tweets please
    'include_retweets' => 0,    //do not include retweets
    'exclude_replies'  => 1     //exclude replies
);

$user = get_option('swt_twitter_link');

//get tweets (cached for 5 hours)
$tweets = $fetcher->get_tweets( $user, $args );

```

**Comment by sentisoft** [comment]
I try with this code you write before and try again but this is what I do not understand why its not want to work.... when I add this part of code $user = get_option('swt_twitter_link'); and then add echo $user .. I get exactly string what I wrote in Theme Options.. but when I add this $tweets = $fetcher->get_tweets( $user, $args ); I just get blank load tweets... But why??? I can not understand... why variable $user not want to work in $tweets = $fetcher->get_tweets( $user, $args ); ...

**Comment by bradvin** [comment]
what twitter user are you trying this for?

**Comment by sentisoft** [comment]
for example... in Theme options I have this http://prntscr.com/280xlw .. I write username sentisoft.... and in your script I add 

```
$user = get_option('swt_twitter_link');
//get tweets (cached for 5 hours)
$tweets = $fetcher->get_tweets( $user, $args );
```

but this not want to work... I am not sure why is this happen?? in other part of my theme get_option('swt_twitter_link') work okay..

**Comment by sentisoft** [comment]
Its look like nobady try to add this with wordpress theme options yet :) Or I doing something wrong??

**Comment by sentisoft** [comment]
okay.. just one question... Can I use my own twitter API for another user? The idea is to 10 user go with my twitter API.. is this can be done..?

**Comment by sentisoft** [comment]
Okay.. I done it.. here is how .. 

```
function tweet_username () { 
    $user = get_option('swt_twitter_link');
    return $user;
}

//get tweets (cached for 5 hours)
$tweets = $fetcher->get_tweets( tweet_username (), $args );
```

Now I am not sure is this best option but with just simple get_option not want to work only like this

**Comment by bradvin** [comment]
glad you figured it out
