### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by dameer** [fooplugins/FooTweetFetcher#3]
How about this one:

Notice: Undefined variable: meta

**Comment by bradvin** [comment]
You are using the example_usage.php code direclty. That file is only to show you usage.
In there `$meta["twitterUser"]` is being used which you need to swop out with an actual twitter name

**Comment by dameer** [comment]
Yeah, I've figured that out, thanks mate! Still it would be much easier for a rookie to omit that array-like placeholder and have something like:

<pre><code>$tweets = $fetcher->get_tweets( TWITTER_USER_NAME, $args );</code></pre>

No matter what take my apologies for the false alert. I appreciate your Tweet Fetcher and the work you put into!

**Comment by bradvin** [comment]
Ye, that does make sense. I have removed the $meta array and replace with a fake string
