### ISSUE TITLE
get_transient problem

### ISSUE THREAD

**Issue by GoldSmyth** [fooplugins/FooTweetFetcher#6]
Hi,

I'm having an issue with the set/get transient functionality... When the transient runs to zero, it returns an array of new data as normal, although when it pulls this data from the transient, it returns a string which can't be looped and displayed.  

I have tried serializing the data coming out to change the string back to an array, but comes up with an error.

Great little script btw, hoping you can help :)

**Comment by bradvin** [comment]
hi there,

can you please paste the exact php error you are getting including the line number in which php file

**Comment by GoldSmyth** [comment]
I have error reporting turned on, but there is no error with the script.

my issue is with the file FooTweetFetcher.php.

on line 32, the transient is set with the array $data from the twitter API, but when it comes out again to be used on line 27, it is returned as a string, and NOT an array like it is when the the data is fetched fresh from the twitter API.

$data is an array going into the transient, but comes out as a string.

which in turn causes the example_usage.php to fail on line 31, where it checks to see if $tweets is an array, which it isn't (as it has been returned as a string).

So I get my fresh tweets from the API displayed the first time, but when they're pulled from the transient, nothing is displayed.

Hope this made sense.

I'm using PHP Version 5.4.10, and WordPress 4.1

**Comment by GoldSmyth** [comment]
Hi I figured out the problem, I was getting some bad data back from a tweet that was breaking the array with a series of brackets.

Sorry if I wasted your time, and thanks again for the script.
